#!/bin/bash
#BSUB -J poisson_mpi_cuda
#BSUB -o poisson_mpi_cuda_%J.out
#BSUB -e poisson_mpi_cuda_%J.err
#BSUB -n 10
#BSUB -W 00:15
#BSUB -gpu "num=2:mode=shared:mps=yes"



# Проверка сборки
if [ ! -f bin/poisson_mpi_cuda ]; then
    echo "Error: bin/poisson_mpi_cuda not built"
    exit 1
fi

echo ""
echo "=== Running MPI+CUDA version ==="


module load SpectrumMPI

# Запуск программы
mpirun -n 10 ./bin/poisson_mpi_cuda --M 2000 --N 3200
echo ""
echo "=== Job completed ==="
